# the "trigger" and "pr" settings define when
# the pipeline will run automatically

# simple trigger: list of branches
# trigger:
# - master
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

# pr trigger: automatic builds on pull requests
# targetting certain branches
# default is all pull requests
pr:
- master

variables:
  solutionPath: Website

jobs:
- job: build_linux
  # pool section defines what agent the job will run on
  pool:
    # get a microsoft-hosted agent running the latest ubuntu linux.
    vmImage: 'ubuntu-latest'

  # job has steps
  steps:
  - task: SonarCloudPrepare@1
    displayName: sonarcloud prepare analysis
    inputs:
      SonarCloud: 'sonarcloud-dusten'
      organization: '2006-jun15-net'
      scannerMode: 'MSBuild'
      projectKey: '2006-jun15-net_dusten-project1'
      extraProperties: |
        sonar.exclusions=**/lib/**
        sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)/*.trx
        sonar.cs.opencover.reportsPaths=$(Agent.TempDirectory)/*/coverage.opencover.xml

  - script: dotnet build -c Release
    displayName: dotnet build
    workingDirectory: $(solutionPath)
    
  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: 'test'
      projects: '$(solutionPath)'
      arguments: '-c Release --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura,opencover'
      testRunTitle: 'ubuntu'

  - task: SonarCloudAnalyze@1
    displayName: sonarcloud run analysis

  - task: SonarCloudPublish@1
    displayName: publish sonarcloud result
    inputs:
      pollingTimeoutSec: '300'

  - task: PublishCodeCoverageResults@1
    displayName: publish code coverage
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(Agent.TempDirectory)/*/coverage.cobertura.xml'
      failIfCoverageEmpty: true

  - script: dotnet publish -c Release -o ../publish
    displayName: dotnet publish
    workingDirectory: $(solutionPath)

  - task: AzureRmWebAppDeployment@4
    displayName: azure app service deploy
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure subscription 1(3c19313e-3624-464d-916e-a83d2254b3d7)'
      appType: 'webApp'
      WebAppName: '2006-project1-knull'
      packageForLinux: '$(System.DefaultWorkingDirectory)/publish'

- job: build_windows

  pool:
    vmImage: windows-latest
    
  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
    system.debug: true
  
  steps:
  - task: NuGetToolInstaller@1
    displayName: install nuget
    inputs:
      versionSpec:

  - task: NuGetCommand@2
    displayName: nuget restore
    inputs:
      command: 'restore'
      restoreSolution: '$(solution)'
      feedsToUse: 'select'

  - task: VSBuild@1
    displayName: visual studio build
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: VSTest@2
    displayName: visual studio test
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\*test*.dll
        !**\*TestAdapter.dll
        !**\obj\**
      searchFolder: '$(System.DefaultWorkingDirectory)'
      codeCoverageEnabled: true
      testRunTitle: 'windows'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
