apiVersion: v1
kind: Secret
metadata:
  name: db-secret
data:
  connection-str: U2VydmVyPXRjcDoyMDIwLWtudWxsLmRhdGFiYXNlLndpbmRvd3MubmV0LDE0MzM7SW5pdGlhbCBDYXRhbG9nPVByb2plY3QwO1BlcnNpc3QgU2VjdXJpdHkgSW5mbz1GYWxzZTtVc2VyIElEPXNlbWljb2xvbjtQYXNzd29yZD1TdGgyMTM3MjtNdWx0aXBsZUFjdGl2ZVJlc3VsdFNldHM9RmFsc2U7RW5jcnlwdD1UcnVlO1RydXN0U2VydmVyQ2VydGlmaWNhdGU9RmFsc2U7Q29ubmVjdGlvbiBUaW1lb3V0PTMwOwo=
