apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dustenproject1 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dustenproject1 
    spec:
      containers:
        - name: dustenproject1 
          image: project1container.azurecr.io/dustenproject1
          ports:
          - containerPort: 80